################################################################################
# ENVIRONMENT TEMPLATES
################################################################################

# can't merge arrays in YAML so we have to duplicate stuff between 36 and 37
# and include all variables that are relevant across all operating systems
py_env_settings:
  - setting: &env_py36
      env:
        - PYTHON_VERSION=3.6.8
        - PY_MM=36
        - TOXENV=py${PY_MM}
        - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
  - setting: &env_py37
      env:
        - PYTHON_VERSION=3.7.6
        - PY_MM=37
        - TOXENV=py${PY_MM}
        - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
  - setting: &env_py38
      env:
        - PYTHON_VERSION=3.8.1
        - PY_MM=38
        - TOXENV=py${PY_MM}
        - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH

################################################################################
# OS JOB TEMPLATES
################################################################################

stages:
  - setup
  - build

job_templates:
  - job: &ubuntu_setup_job
      stage: setup
      services: docker
      os: linux
      language: shell
      cache: dependencies
      workspaces:
        create:
          name: dependencies-linux
          paths: ./dependencies
      script:
        - chmod +x .travis/check_opencv_manylinux.sh
        - .travis/check_opencv_manylinux.sh
        - find ./dependencies

  - job: &win_setup_job
      stage: setup
      os: windows
      language: shell
      cache: dependencies
      workspaces:
        create:
          name: dependencies-win
          paths: ./dependencies
      script:
        - .travis/setup_opencv_win.sh

  - job: &manylinux_base_job
      stage: build
      services: docker
      os: linux
      language: shell
      workspaces:
        use: dependencies-linux
      script:
        - chmod +x .travis/build_wheels_manylinux.sh
        - export OpenCV_DIR=${PWD}/dependencies/opencv
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PWD}/dependencies/opencv/lib64
        - docker run --rm -e PY_MM=$PY_MM -v `pwd`:/io quay.io/pypa/manylinux2014_x86_64 /io/.travis/build_wheels_manylinux.sh

  - job: &win_base_job
      stage: build
      os: windows
      language: shell
      workspaces:
        use: dependencies-win
      install:
        - choco install python --version $PYTHON_VERSION
        - python -m pip install -U pip
      before_script:
        - export OpenCV_DIR=${PWD}/dependencies/opencv
        - pip wheel . -w dist --no-deps
      script:
        - pip install dist/*.whl
        - export PATH=${OpenCV_DIR}/x64/vc15/bin:$PATH
        - python -c "from pure_detector import PuReDetector"

################################################################################
# DEFINE JOB MATRIX
################################################################################

jobs:
  include:

    - name: "OpenCV for Manylinux"
      <<: *ubuntu_setup_job

    - name: "Python 3.6.8 on Manylinux"
      <<: *manylinux_base_job
      <<: *env_py36

    - name: "Python 3.7.6 on Manylinux"
      <<: *manylinux_base_job
      <<: *env_py37

    - name: "Python 3.8.1 on Manylinux"
      <<: *manylinux_base_job
      <<: *env_py38

    # - name: "OpenCV for Windows"
    #   <<: *win_setup_job

    # - name: "Python 3.6.8 on Windows"
    #   <<: *win_base_job
    #   <<: *env_py36

    # - name: "Python 3.7.6 on Windows"
    #   <<: *win_base_job
    #   <<: *env_py37

    # - name: "Python 3.8.1 on Windows"
    #   <<: *win_base_job
    #   <<: *env_py38

# deploy:
#   provider: releases
#   on:
#     all_branches: true
#     tags: false
#   name: "Travis Build for $TRAVIS_COMMIT"
#   body: "Testing automated builds."
#   skip_cleanup: true
#   draft: true
#   api_key: $GitHubOAUTH
#   file_glob: true
#   file: ./dist/*
