################################################################################
# ENVIRONMENT TEMPLATES
################################################################################

# can't merge arrays in YAML so we have to duplicate stuff between 36 and 37
# and include all variables that are relevant across all operating systems
py_env_settings:
  - setting: &env_py36
      env:
        - PYTHON_VERSION=3.6.8
        - PY_MM=36
        - TOXENV=py${PY_MM}
        - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
  - setting: &env_py37
      env:
        - PYTHON_VERSION=3.7.6
        - PY_MM=37
        - TOXENV=py${PY_MM}
        - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
  - setting: &env_py38
      env:
        - PYTHON_VERSION=3.8.1
        - PY_MM=38
        - TOXENV=py${PY_MM}
        - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH

################################################################################
# OS JOB TEMPLATES
################################################################################

stages:
  - setup
  - main
  - deploy

base_jobs:
  - job: &win_setup_job
      stage: setup
      os: windows
      language: shell
      cache: dependencies
      workspaces:
        create:
          name: dependencies
          paths: ./dependencies
      script:
        - .travis/win_dependencies.sh

  - job: &win_base_job
      stage: main
      os: windows
      language: shell
      workspaces:
        use: dependencies
        create:
          name: win-dist
          paths: ./dist
      install:
        - export OpenCV_DIR=${PWD}/dependencies/opencv
        - export PATH=${OpenCV_DIR}/x64/vc15/bin:$PATH
        - choco install python --version $PYTHON_VERSION
        - python -m pip install -U pip
      before_script:
        - pip wheel . -w dist --no-deps
        - ls dist
        - pip install dist/*.whl
      script:
        - python -c "from pure_detector import PuReDetector"
        - mv dist/* /dist

  - job: &deploy_job
      stage: deploy
      workspaces:
        use: win-dist
      script: find /c/
      # deploy:
      #   provider: releases
      #   on:
      #     all_branches: true
      #     tags: false
      #   name: "Travis Build for $TRAVIS_COMMIT"
      #   body: "Testing automated builds."
      #   skip_cleanup: true
      #   draft: true
      #   api_key: $GitHubOAUTH
      #   file_glob: true
      #   file: "/dist/*"

################################################################################
# DEFINE JOB MATRIX
################################################################################

before_install: pwd

jobs:
  include:
    - name: "Windows Setup"
      <<: *win_setup_job

    - name: "Python 3.6.8 on Windows"
      <<: *win_base_job
      <<: *env_py36

    - name: "Python 3.7.6 on Windows"
      <<: *win_base_job
      <<: *env_py37

    - name: "Python 3.8.1 on Windows"
      <<: *win_base_job
      <<: *env_py38

    - name: "Deployment"
      <<: *deploy_job
