[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "numpy", # need to link against numpy
    "cython",
]
build-backend = "setuptools.build_meta"
